# Modified theme

if patched_font_in_use; then
    TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="⮂"
    TMUX_POWERLINE_SEPARATOR_LEFT_THIN="⮃"
    TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="⮀"
    TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="⮁"
else
    TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="||"
    TMUX_POWERLINE_SEPARATOR_LEFT_THIN="||"
    TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="||"
    TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="||"
fi
# TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
# TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='196'
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'255'}

TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
    TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
        # "os 251 231" \
        "tmux_session_info 148 234" \
        "battery 60 225" \
        "ifstat 30 255" \
    )
fi

# if is macos
if [[ "$OSTYPE" == "darwin"* ]]; then
    if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
        TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
            "hname 0 253" \
            "nt 237 253" \
            "cpu 240 214" \
            # memory usage on mac is not accurate
            # "load 237 167" \
            "date 30 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
            "time 60 225 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
        )
    fi
else
    if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
        TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
            "hname 0 253" \
            "nt 237 253" \
            "cpu 240 214" \
            # "load 237 167" \
            "date 30 255 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
            "time 60 225 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
        )
    fi
fi

